version: "3.8"

services: 
  app:
    build: .
    container_name: app-staffer
    restart: always
    depends_on: 
      - mysql
    environment:
      - SERVER_PORT=9090
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password123
      - DB_NAME=worker
    ports:
      - 9090:9090
  
  mysql:
    container_name: mysql
    restart: always
    build: ./database/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=password123