version: "3.8"

services: 
  app:
    build: .
    container_name: app-staffer
    restart: always
    ports:
      - 9090:9090
    environment:
      - SERVER_PORT=9090
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password123
      - DB_NAME=worker
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=password123
    volumes:
      - ./employee.sql:/docker-entrypoint-initdb.d/employee.sql